### PR TITLE
Data atlas

### PR DESCRIPTION
**Pull request by ggalibert**

### CODE REVIEW

**Comment by xhoenner** [comment]
This looks all good to me GG.

How about adding (1) a constraint like we do in the harvesters to check that the geometry is valid, and (2) a GIST index on the geometry?

**Comment by ggalibert** [comment]
1) Why not, how do we do that?
2) No idea how to do that. What would be the benefit?

**Comment by xhoenner** [comment]
1) ALTER TABLE data_atlas ADD CONSTRAINT data_atlas_geom_check CHECK (st_isvalid(geom));
2) CREATE INDEX data_atlas_gist_idx ON data_atlas USING gist (geom);

See https://docs.google.com/document/d/1-E05wDMvI_Yy2Zz9m3D8DCWUjjkhPDJFm_jr9TvbUgc/edit#heading=h.ar3f0toh9kfn for details about GIST index

**Comment by ggalibert** [comment]
Thanks Xavier, I've just included those changes.

**Comment by xhoenner** [comment]
Great, thanks! Do you want to include in that PR your SQL query that populates the data_atlas table?

**Comment by ggalibert** [comment]
Still working on it and can include it later.

**Pull request merged**
